baseurl = "http://biodocker.org/"
languageCode = "en-us"
title = "BioDocker"
theme = "hugo-creative-theme"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more informtion take a look at the README.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "BioDocker"
	description = "BioDocker: An open-source and community-driven framework for software standardization"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "BioDocker Project"

		[params.navigation.links]
			about     = "Registry"
			services  = "GitHub"
			portfolio = "Documentation"
			contact   = "About"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Bioinformatics more Accessible & Reproducible"
		subtitle   = "[BioDocker] (http://biodocker.org) is an open source and community-driven framework which provides system-agnostic executable environments for bioinformatics software. BioDocker is based on the popular [Docker](http://www.docker.com) framework that allows software to be installed and executed under an isolated and controllable environment."
		docsText = "Docs"
		aboutText = "Find More"
		community = "Community"
		github    = "GitHub"


	# About section
	[params.about]
		headline    = "We've got what you need!"
		description = "[BioDocker Registry](http://status-biodocker.rhcloud.com/) provides a list of all containers ready to be use!!"
		buttonText  = "Check The Registry"
		registry    = "http://status-biodocker.rhcloud.com/"


	# Service section
	[params.services]
		headline = "BioDocker on GitHub"

        [[params.services.list]]
            icon = "fa-cloud-download"
            title = "Containers"
            description = "Find out the BioDocker containers"
            href = "https://github.com/BioDocker/containers"

        [[params.services.list]]
			icon = "fa-question-circle"
			title = "Ask for a container"
			description = "Request a container to the BioDocker community"
			href = "https://github.com/BioDocker/containers/issues"

		[[params.services.list]]
            icon = "fa-plus-square"
            title = "Sandbox"
            description = "Workplace for new or broken containers"
            href = "https://github.com/BioDocker/sandbox"

        [[params.services.list]]
            icon = "fa-book"
            title = "Specifications"
            description = "Read about BioDocker specification and guidelines"
            href = "https://github.com/BioDocker/biodocker"


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Get Started with BioDocker"

		[params.aside.button]
			text = "Documentation"
			link = "docs"

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Ready to start your next project with us? That's great! Send us an email and we will get back to you as soon as possible!"
		phone = "Contribute with us"
		refphone = "https://github.com/BioDocker/biodocker/blob/master/CONTRIBUTING.md"
		email = "biodockers@gmail.com"
